### ISSUE TITLE
securityContext -- runAsUser "id>0", ....

### ISSUE THREAD

**Issue by peddyspg** [Portshift/kubei#20]
We have a PSP, so every deployment must have a statement like:

          securityContext:
            runAsUser: 900
            runAsGroup: 900
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all

or if needed
          securityContext:
            runAsUser: 900
            runAsGroup: 900
            runAsNonRoot: false
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - all

I suppose, postgres does not need root-privileges?

**Comment by FrimIdan** [comment]
Hi @peddyspg sorry for the late response.
postgres does not need root-privileges but the user must be well define in the docker file during the docker build and can be changed with the a securityContext  - we use user 26.
The following security context will work:
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          runAsGroup: 26
          runAsNonRoot: true
          runAsUser: 26 
```

You may create a specific PSP policy for the clair-db workload. 

Hope it helps and you will be able to use Kubei.
